name: Reusable
on:
    workflow_call:
      inputs:
        artifact-name:
          description: The name of deployment package
          required: false
          type: string
          default: dist
      outputs:
        results:
          description: The results of build
          value: ${{ jobs.deploy.outputs.outcome }}
    #   secrets:
    #     some-sectrets:
    #       required: true
jobs:
  deploy:
    outputs:
        outcome: ${{ steps.setup-results.outputs.step-results }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls -al
      - name: Deploying
        run: |
          echo "Deploying..."
      - name: Setup results
        id: setup-results
        run: |
          echo "step-results=sucess" >> $GITHUB_OUTPUT
